version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
  environment:
    NODE_ENV: production
    EMAIL_HOST: smtp.titan.email
    EMAIL_PORT: 465
    EMAIL_USER: hello@seemetracker.com
    EMAIL_PASS: "Seemetracker123#"
    DATABASE_URI: mongodb+srv://velox:velox@cluster0.tinnxfh.mongodb.net/waitlist?retryWrites=true&w=majority

    depends_on:
      - mongo
    command: yarn start

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: velox
      MONGO_INITDB_ROOT_PASSWORD: velox

  yarn:
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: yarn
